// packages/cli/tests/integration/skill-catalog-consistency.test.ts
//
// Vocabulary & catalog regression lock for `initialize-harness-project`.
//
// Each assertion below guards against a SPECIFIC regression that already
// happened in this repo — restating the motivation here so a future reader
// does not weaken or delete an assert without first understanding the
// history it protects.
//
// (a) skill.yaml description appears verbatim in skills-catalog.md
//     REGRESSION GUARDED: drift between `skill.yaml` and the generated
//     `docs/reference/skills-catalog.md` (the catalog is regenerated by
//     `pnpm run generate-docs`; a description edit that skips regen leaves
//     the catalog stale). Spec source: init-design-roadmap-config #15
//     (Phase 5 verification report).
//
// (b) SKILL.md references both `harness-roadmap` (creator) and
//     `manage_roadmap` (entry-management MCP tool)
//     REGRESSION GUARDED: the pre-Phase-4 init flow conflated the two —
//     SKILL.md described "create roadmap via manage_roadmap", which is
//     the WRONG tool for creation. Phase 4 of init-design-roadmap-config
//     split the responsibility: `harness-roadmap` skill creates,
//     `manage_roadmap` MCP tool adds/edits entries. This assert ensures
//     both names remain mentioned so neither half of the split disappears.
//
// (c) SKILL.md does NOT contain the regression string "created via
//     manage_roadmap"
//     REGRESSION GUARDED: that exact phrase was the pre-Phase-4 wording
//     of the conflated model (see assert (b)). Phase 4 of
//     init-design-roadmap-config rewrote every occurrence; this assert
//     prevents the old wording from sneaking back via a careless edit or
//     a merge from an old branch.
//
// (d) `Not sure yet` outside `emit_interaction` button labels fails
//     REGRESSION GUARDED: init-design-roadmap-polish FINAL-S2 normalized
//     narrative copy to lowercase `not sure` (no "yet", no hyphen), but
//     the literal "Not sure yet" survives as a verbatim button-label
//     string inside `emit_interaction` options (carries the
//     "you-can-decide-later" UX affordance). Per D5, this assert tightens
//     the window so any non-button "Not sure yet" — narrative prose,
//     headings, table cells — fails the suite. Without this guard, the
//     vocabulary drift FINAL-S2 closed would re-open on the next edit.
//
// (e) hyphenated `not-sure` appears nowhere in user-facing copy
//     REGRESSION GUARDED: the hyphenated form reads as an identifier
//     shape (e.g. `design.enabled`), not prose. Per D3 it survives only
//     as a config key or TypeScript string-literal union (e.g.
//     `InitFixtureScenario.design: 'yes' | 'no' | 'not-sure'` in
//     `_helpers/init-fixture.ts` — D3 technical-identifier carve-out, OUT
//     of scope for this assert). The assert scope is intentionally narrow:
//     `SKILL.md` and `init-design-roadmap-config/proposal.md` only. The
//     polish proposal.md is excluded because it contains a code-fence
//     literal of the technical-identifier carve-out; `_helpers/` is
//     excluded per Phase 3 PD9. Residual hyphenated matches in
//     init-design-roadmap-config/plans/ + /verification/ are out of
//     scope per Phase 2 verifier scope-note (historical paper trail).
//
// Spec: docs/changes/init-design-roadmap-polish/proposal.md (FINAL-S3, D4, D5, D10).
// Plan: docs/changes/init-design-roadmap-polish/plans/2026-06-03-phase4-docstring-regression-guard-plan.md
import { describe, it, expect } from 'vitest';
import * as path from 'path';
import * as fs from 'fs';

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..', '..');
const SKILL_YAML = path.join(
  REPO_ROOT,
  'agents',
  'skills',
  'claude-code',
  'initialize-harness-project',
  'skill.yaml'
);
const SKILL_MD = path.join(
  REPO_ROOT,
  'agents',
  'skills',
  'claude-code',
  'initialize-harness-project',
  'SKILL.md'
);
const CATALOG = path.join(REPO_ROOT, 'docs', 'reference', 'skills-catalog.md');
const PROPOSAL_MD = path.join(
  REPO_ROOT,
  'docs',
  'changes',
  'init-design-roadmap-config',
  'proposal.md'
);

function extractDescription(yamlText: string): string {
  const match = yamlText.match(/^description:\s*(.*)$/m);
  if (!match) throw new Error('description field not found in skill.yaml');
  return match[1].trim().replace(/^["']|["']$/g, '');
}

describe('skill catalog ↔ SKILL.md consistency (spec #15)', () => {
  it('skill.yaml description appears verbatim in skills-catalog.md under initialize-harness-project', () => {
    const yamlText = fs.readFileSync(SKILL_YAML, 'utf-8');
    const description = extractDescription(yamlText);
    expect(description).toContain('design system');
    expect(description).toContain('roadmap configuration');

    const catalog = fs.readFileSync(CATALOG, 'utf-8');
    expect(catalog).toContain(description);
  });

  it('SKILL.md references both harness-roadmap (creator) and manage_roadmap (MCP tool)', () => {
    const md = fs.readFileSync(SKILL_MD, 'utf-8');
    expect(md).toContain('harness-roadmap');
    expect(md).toContain('manage_roadmap');
  });

  it('SKILL.md does NOT contain the regression string "created via manage_roadmap"', () => {
    const md = fs.readFileSync(SKILL_MD, 'utf-8');
    expect(md).not.toMatch(/created via manage_roadmap/);
  });

  it('forbids "Not sure yet" outside emit_interaction button labels', () => {
    const skillMd = fs.readFileSync(SKILL_MD, 'utf-8');
    const occurrences = [...skillMd.matchAll(/Not sure yet/g)];
    for (const m of occurrences) {
      const window = skillMd.slice(Math.max(0, m.index! - 32), m.index! + 16);
      expect(window).toMatch(/label:\s*["']Not sure yet/);
    }
  });

  it('forbids hyphenated "not-sure" in user-facing copy', () => {
    // Scope is intentionally narrow per spec D3 + D4 and the Phase 2
    // verifier scope-note:
    //   - SKILL_MD: user-facing skill prose.
    //   - PROPOSAL_MD: init-design-roadmap-config/proposal.md only.
    // EXCLUDED:
    //   - docs/changes/init-design-roadmap-polish/proposal.md — contains a
    //     code-fence TypeScript literal `'not-sure'` in the
    //     InitFixtureScenario.design union (D3 technical-identifier
    //     carve-out).
    //   - packages/cli/tests/integration/_helpers/init-fixture.ts — same
    //     D3 carve-out (Phase 3 PD9).
    //   - docs/changes/init-design-roadmap-config/plans/ + /verification/ —
    //     historical paper trail; out of scope per Phase 2 verifier
    //     scope-note (15 residual matches there are intentional history).
    for (const filePath of [SKILL_MD, PROPOSAL_MD]) {
      const content = fs.readFileSync(filePath, 'utf-8');
      expect(content).not.toMatch(/not-sure/);
    }
  });
});
