import { describe, it, expect } from 'vitest';
import {
  renderCodexSkill,
  renderCodexOpenaiYaml,
  renderCodexAgentsMd,
} from '../../src/slash-commands/render-codex';
import type { SlashCommandSpec } from '../../src/slash-commands/types';

const baseSpec: SlashCommandSpec = {
  name: 'brainstorming',
  namespace: 'harness',
  fullName: 'harness:brainstorming',
  description: 'Structured ideation and exploration with harness methodology',
  version: '1.0.0',
  cognitiveMode: 'constructive-architect',
  tools: ['Read', 'Write', 'Bash'],
  args: [{ name: 'path', description: 'Project path', required: false }],
  skillYamlName: 'harness-brainstorming',
  sourceDir: 'harness-brainstorming',
  skillsBaseDir: 'agents/skills/claude-code',
  prompt: {
    context: 'Cognitive mode: constructive-architect\nType: rigid',
    objective: 'Structured ideation and exploration',
    executionContext: '@agents/skills/claude-code/harness-brainstorming/SKILL.md',
    process: '1. Read SKILL.md and follow its workflow directly',
  },
};

const skillMdContent = '# Harness Brainstorming\n\nExplore ideas systematically.';

describe('renderCodexSkill', () => {
  it('emits YAML frontmatter with name and description for Codex skill discovery', () => {
    const output = renderCodexSkill(skillMdContent, baseSpec);
    const lines = output.split('\n');
    expect(lines[0]).toBe('---');
    expect(output).toMatch(/^---\n.*name: harness-brainstorming/s);
    expect(output).toMatch(
      /description: Structured ideation and exploration with harness methodology/
    );
    const closeIdx = lines.findIndex((line, i) => i > 0 && line === '---');
    expect(closeIdx).toBeGreaterThan(0);
  });

  it('preserves the original SKILL.md body after the frontmatter', () => {
    const output = renderCodexSkill(skillMdContent, baseSpec);
    expect(output).toContain('# Harness Brainstorming');
    expect(output).toContain('Explore ideas systematically.');
  });

  it('includes the generated-by header so orphan detection can find files', () => {
    const output = renderCodexSkill(skillMdContent, baseSpec);
    expect(output).toContain('Generated by harness generate-slash-commands');
  });

  it('escapes a description containing a colon by quoting it', () => {
    const spec = { ...baseSpec, description: 'Skill: with colon in description' };
    const output = renderCodexSkill(skillMdContent, spec);
    expect(output).toMatch(/description: "Skill: with colon in description"/);
  });

  it('escapes embedded double quotes in description', () => {
    const spec = { ...baseSpec, description: 'Skill with "quoted" word' };
    const output = renderCodexSkill(skillMdContent, spec);
    expect(output).toMatch(/description: "Skill with \\"quoted\\" word"/);
  });
});

describe('renderCodexOpenaiYaml', () => {
  it('emits real metadata (no longer a Phase B placeholder)', () => {
    const output = renderCodexOpenaiYaml(baseSpec);
    expect(output).not.toContain('Reserved for Phase B');
    expect(output).toContain('name: harness-brainstorming');
    expect(output).toContain(
      'description: Structured ideation and exploration with harness methodology'
    );
    expect(output).toContain('version: "1.0.0"');
  });

  it('quotes a description containing a colon', () => {
    const spec = { ...baseSpec, description: 'A: B' };
    const output = renderCodexOpenaiYaml(spec);
    expect(output).toContain('description: "A: B"');
  });
});

describe('renderCodexAgentsMd', () => {
  const specs = [
    baseSpec,
    {
      ...baseSpec,
      name: 'execution',
      skillYamlName: 'harness-execution',
      description: 'Execute plans',
    },
  ];

  it('includes a heading and intro paragraph', () => {
    const output = renderCodexAgentsMd(specs);
    expect(output).toContain('# Harness Skills');
  });

  it('lists all skill names', () => {
    const output = renderCodexAgentsMd(specs);
    expect(output).toContain('harness-brainstorming');
    expect(output).toContain('harness-execution');
  });

  it('includes skill descriptions', () => {
    const output = renderCodexAgentsMd(specs);
    expect(output).toContain('Structured ideation and exploration with harness methodology');
    expect(output).toContain('Execute plans');
  });

  it('includes the generated header', () => {
    const output = renderCodexAgentsMd(specs);
    expect(output).toContain('Generated by harness generate-slash-commands');
  });
});
